In [5]:
import numpy as np
import random

class NN():
    """
    Class for a neural network. Requires input/output sizes, number of hidden layers, and number of neurons
    at each layer (we assume all hidden layers are of the same size)
    """
    def __init__(self, input_size, num_HL, hidden_size, output_size):
        # Initialize by setting random 
        self.input_size = input_size
        self.hidden_layers = num_HL
        # NOTE we are assuming all hidden layers are the same size
        self.hidden_size = hidden_size
        self.output_size = output_size
        # Activations for each neuron
        # + 1 for bias neuron
        self.activations_in = np.ones(self.input_size + 1)
        # Hidden can comprise multiple layers, so we have a matrix
        # + 1 for bias neuron
        self.activations_hidden = np.ones((self.hidden_layers, self.hidden_size + 1))
        self.activations_out = np.ones(self.output_size)
        # Weights of all the edges, randomized for good results
        # PLUS ONE FOR BIASES
        self.weights_in = np.random.randn(self.input_size + 1, self.hidden_size)
        self.weights_in = np.column_stack((self.weights_in, np.zeros(self.input_size + 1)))
        # We will only have hidden weights if there are multiple hidden layers
        if self.hidden_layers > 1:
            self.weights_hidden = np.random.randn(self.hidden_layers - 1, self.hidden_size + 1, self.hidden_size + 1)
            # Set the weights corresponding with next layers biases to 0
            for weights in self.weights_hidden:
                weights[-1] = 0.0
        else:
            self.weights_hidden = []
        # No plus one for output, as it should not have a bias parameter
        self.weights_out = np.random.randn(self.hidden_size + 1, self.output_size)
        # To be valued when train() is called
        self.learning_rate = 0.0

        # Instantiate deltas for holding gradients
        self.Deltas_hidden = []
        self.deltas_out = []
    
    def _sigmoid(self, x):
        """
        Sigmoid function for calculating a distribution over 2 classes
        """
        return 1 / (1 + np.exp(-x))
    
    def _derivative_sigmoid(self, x):
        """
        Derivative of the sigmoid function where x = the output of the sigmoid
        
        This can be used in backpropogation, wherein we would have 
        already computed the sigmoid in the forward pass, and we can draw upon its cached value
        """
        return self._sigmoid(x) * (1.0 - self._sigmoid(x))
    
    def _softmax(self, x):
        exponentials = [np.exp(p) for p in x]
        denominator = sum(exponentials)
        return [p / denominator for p in exponentials]
    
    def _relu(self, x):
        """
        relu function used for activation
        """
        return max(x, 0.0)
    
    def _derivative_relu(self, x):
        """
        Derivative of the relu function, the input will be the output of the relu function.
        This is because in practice we will have already performed this computation in the forward pass
        so in the backward pass, we need to find its derivative drawing upon the cached relu(x).
        """
        return 1 if x > 0.0 else 0.0
    
    def _binary_cross_ent(self, y_hat, y):
        """
        This basically finds the negative of the log probability of class1 - its inverse
        """
        return (-y * np.log(y_hat)) - ((1 - y) * np.log(1 - y_hat))
    
    def _negative_log_likelihood(self, y_hat):
        return -np.log(y_hat)
    
    def _derivative_negative_log_likelihood(self, y_hat):
        return -1/y_hat
    
    def _derivative_binary_cross_ent(self, y_hat, y):
        """
        Derivative of binary cross-entropy
        
        This description is misleading. 
        This is the part of the partial derivative of binary cross-entropy 
        w.r.t the parameters of our function. In practice, the other part is 
        the dot product of this and the activations (activate(w, x))
        """
        #return -(y / y_hat) - ((1 - y) / (1 - y_hat))
        return (y_hat - y)

    def _activate(self, x):
        """
        RELU for non-linear activation function
        """
        return self._relu(x)
    
    def _activate_vector(self, X):
        """
        Run on a numpy vector
        """
        activations = np.vectorize(self._activate)
        return activations(X)
    
    def _derivative_activation(self, x):
        """
        Compute the derivative of the activation function given the activation output
        
        x: activate(node)
        """
        return self._derivative_relu(x)
    
    def _derivative_vector_activation(self, X):
        """
        Derivative for each scalar in a numpy vector
        """
        derivative_activations = np.vectorize(self._derivative_activation)
        return derivative_activations(X)

    def _loss(self, y_hat, y):
        """
        y_hat: sofmax vector
        y:     one-hot vector for the target
        
        Here we will plug in the negative_log_likelihood
        in order to be able to compare the proability of our output at
        the correct class, to 1.
        """
        
        """
        Get the index of the correct class 
        (numpy will return a tuple of the index in each dimension)
        """
        
        # Get the first (and only) dim, and the first (and only) index
        i = np.where(y==1)[0][0]
        return self._negative_log_likelihood(y_hat[i])
    
    def _derivative_loss(self, y_hat, y):
        """
        This will be used in backprop for finding L'(output_layer_node)
        """
        # Get the first (and only) dim, and the first (and only) index
        i = np.where(y==1)[0][0]
        return self._derivative_negative_log_likelihood(y_hat[i])
    
    def _targets_to_one_hots(self, targets):
        """
        Interpret a vector of targets into a matrix
        of one-hot representations
        """
        # Get the number of unique target classes
        num_classes = len(set(targets))
        # Instantiate a matrix of one-hot vectors
        # with one row per target, and one col per class
        one_hots = np.zeros((len(targets), num_classes))
        for i, one_hot in enumerate(one_hots):
            # Set the one-hot vector to hae a 1 at its corresponding target slot
            t = targets[i]
            one_hot[t] = 1
            
        return one_hots
        
    def forward(self, inputs):
        """
        Forward pass: Calculate the activations of each neuron
        """
        if len(inputs) != self.input_size:
          raise Exception("That is not the size of the input layer... try %i" % self.input_size)
        
        # Set input activations, no need to actually calculate anything
        for i, inp in enumerate(inputs):
            self.activations_in[i] = inp
        print("INPUT ACTIVATIONS")
        print(self.activations_in)
        # calculate the activations for each hidden layer
        for h_layer_i in range(self.hidden_layers):
            # Need to take previous layer activation value * weights for a given layer
            # Starting with input layer X first hidden layer
            if h_layer_i == 0:
                # multiply the previous layer's activations by its weight vector for this layer's activations
                self.activations_hidden[h_layer_i] = self.activations_in.T.dot(self.weights_in)
                # Reset bias activation to 1.0
                self.activations_hidden[h_layer_i][-1] = 1.0
            else:
                # multiply the previous layer's activations by its weight vector for this layer's activations
                self.activations_hidden[h_layer_i] = self._activate_vector(self.activations_hidden[h_layer_i - 1]).T.dot(self.weights_hidden[h_layer_i - 1])
                # Reset bias activation to 1.0
                self.activations_hidden[h_layer_i][-1] = 1.0

                
        # Output activations will be the dot product of the final hidden layer, and the output weights
        # Activate the vector before, but do not activate the activations_out
        self.activations_out = self._activate_vector(self.activations_hidden[-1]).T.dot(self.weights_out)
        
        #Print all of the weights, to see updates
        """
        print("ACTIVATIONS")
        print(self.activations_in)
        print(self.activations_hidden)
        print(self.activations_out)
        """
        print("WEIGHTS:")
        print(self.weights_in)
        print(self.weights_hidden)
        print(self.weights_out)

    def backward(self, targets):
        """
        Backpropogation for finding the partial derivative of the each node w.r.t the loss function,
        and updating weights based on those gradients
        """
        if len(targets) != len(self.activations_out):
            raise Exception("Your labels are not the same size as your output layer!")
        # Calculate loss - there will be a value for each node in the output layer
        # Take the simoid of the activations of the output layer, because we are doing 2 class classification
        # ***If we have >2 classes, we would use softmax***
        """
        print("ACTIVATIONS IN")
        print(self.activations_in)
        
        print("ACTIVATIONS HIDDEN")
        print(self.activations_hidden)
        
        print("ACTIVATIONS OUT")
        print(self.activations_out)
        """
        
        print("SOFTMAX_LAYER")
        print(self._softmax(self.activations_out))
        """
        print("TARGETS")
        print(targets)
        """
        loss = self._loss(self._softmax(self.activations_out), targets)
        
        """
        Now we need to calculate the partial derivative of the loss w.r.t each weight.
        Think of this as finding the amount that each node contributes to a change in the final loss.
        
        Each node has a value "delta", which represents the partial derivative of the loss w.r.t. its value:
        Use the partial derivative of the loss function, in our case binary cross-entropy
        """
        self.deltas_out = np.zeros([self.output_size])
        derivative_loss = self._derivative_loss(self._softmax(self.activations_out), targets)
        print("LOSS PER INSTANCE: %2f" % loss)
        print("DERIVATIVE LOSS: %2f" % derivative_loss)
        for i, activation_out in enumerate(self.activations_out):
            self.deltas_out[i] = derivative_loss * self._derivative_activation(activation_out)
        
        """
        Find derivative of activation (activation was found in the forward pass) * derivative of the inner function,
        which is the parameter w
        """
        self.Deltas_hidden = np.zeros([self.hidden_layers, self.hidden_size + 1])
        ##############
        #####TODO Needs to go in reverse if we have multiple hidden
        for h_layer_i in range(self.hidden_layers):
            # If it is the last hidden layer, then we look at the activations and deltas
            # of the output layer, not the next hidden layer
            if h_layer_i == self.hidden_layers - 1:
                # Loop over each in hidden activation, +1 for bias
                for h_dim_j in range(self.hidden_size + 1):
                    for k, delta_out in enumerate(self.deltas_out):
                        self.Deltas_hidden[h_layer_i][h_dim_j] += delta_out * self._derivative_activation(self.activations_out[k]) * self.weights_out[h_dim_j][k]
            else:
                # Do the same to find the hidden deltas
                for h_dim_j in range(self.hidden_size + 1):
                    for k, delta_h in enumerate(self.Deltas_hidden[h_layer_i + 1]):
                        self.Deltas_hidden[h_layer_i][h_dim_j] += delta_h * self._derivative_activation(self.activations_hidden[h_layer_i + 1][k]) * self.weights_hidden[h_layer_i][h_dim_j][k]        
        
        self.update_weights()
        return loss
        
    def update_weights(self):
        print("UPDATING WEIGHTS")
        # Now we can use the deltas to adjust each weight by L'(w_i_j)
        # These weights are the edges shared between last hidden layer, and output layer
        # Rows of weights_out correponds with length of last hidden layer
        for i in range(len(self.weights_out)):
            # Cols of weights_out correspinds with length of output layer
            for j in range(len(self.weights_out[i])):
                self.weights_out[i][j] -= self._activate(self.activations_hidden[-1][i])\
                * self._derivative_activation(self.activations_out[j])\
                * self.deltas_out[j]\
                * self.learning_rate
                    
        # Loop over each hidden layer
        for w_i in reversed(range(len(self.weights_hidden))):
            # Rows (i) in the weights for this layer will correspond to the size of the layer BEFORE (hidden or input)
            for i in range(len(self.weights_hidden[w_i])):
                # Cols (j) in these weights will correspond to the size of hidden layer w_i
                for j in range(len(self.weights_hidden[w_i][i])):
                    # We do not want to update the dummy 0 weight going TO the extra bias dimension
                    if j == len(self.weights_hidden[w_i][i]) - 1:
                        continue
                    else:
                        # + 1 for layer before, because we are looping in reverse
                        self.weights_hidden[w_i][i][j] -= self._activate(self.activations_hidden[w_i + 1][i])\
                        * self._derivative_activation(self.activations_hidden[w_i][j])\
                        * self.Deltas_hidden[w_i][j]\
                        * self.learning_rate
                        
        # Rows (i) of weights_in corresponds to size of the input layer
        for i in range(len(self.weights_in)):
            # Cols (j) corresponds to size of the first hidden layer (layer above input layer)
            for j in range(len(self.weights_in[i])):
                # We do not want to update the dummy 0 weight going TO the extra bias dimension
                if j == len(self.weights_in[i]) - 1:
                    continue
                else:
                    self.weights_in[i][j] -= self.activations_in[i]\
                    * self._derivative_activation(self.activations_hidden[0][j])\
                    * self.Deltas_hidden[0][j]\
                    * self.learning_rate
    
    def train(self, inputs, targets, epochs=50, lr=.01):
        self.learning_rate = lr
        one_hot_targets = self._targets_to_one_hots(targets)
        for e in range(epochs):
            print("EPOCH %i" % e)
            """
            SGD - randomize the order of the training samples, and 
            """
            in_out = list(zip(inputs, one_hot_targets))
            random.shuffle(in_out)
            # For tracking average loss over SGD, just for logging
            losses = []
            
            for inp, target in in_out:
                if inp == [-1, -1]:
                    print("TARGET: ")
                    print(target)
                    self.forward(inp)
                    losses.append(self.backward(target))

            print("LOSS: %2f" % (sum(losses)/len(losses)))
            
"""
Note that the 4th param, the size of the output layer, should be the
number of classes
"""
MLP = NN(2, 1, 2, 2)
xor_inputs = [[1, 1], [-1, 1], [-1, -1], [1, -1]]
xor_labels = ([1, 0, 1, 0])
MLP.train(xor_inputs, xor_labels)
"""
class Node(Object):
    def __init__(self):
        
    def 
"""

EPOCH 0
TARGET: 
[ 0.  1.]
INPUT ACTIVATIONS
[-1. -1.  1.]
WEIGHTS:
[[-0.63089808 -1.76408292  0.        ]
 [ 0.1052466  -1.41465687  0.        ]
 [-0.18614852 -0.07818527  0.        ]]
[]
[[-0.42839324  1.41877988]
 [ 0.03603064  0.92414088]
 [-1.61292464  1.52648076]]
SOFTMAX_LAYER
[0.0014712650071702122, 0.9985287349928299]
LOSS PER INSTANCE: 0.001472
DERIVATIVE LOSS: -1.001473
UPDATING WEIGHTS
LOSS: 0.001472
EPOCH 1
TARGET: 
[ 0.  1.]
INPUT ACTIVATIONS
[-1. -1.  1.]
WEIGHTS:
[[-0.64510679 -1.77333795  0.        ]
 [ 0.0910379  -1.42391189  0.        ]
 [-0.17193981 -0.06893025  0.        ]]
[]
[[-0.42839324  1.42217991]
 [ 0.03603064  0.95519211]
 [-1.61292464  1.53649549]]
SOFTMAX_LAYER
[0.001190716340136376, 0.99880928365986354]
LOSS PER INSTANCE: 0.001191
DERIVATIVE LOSS: -1.001192
UPDATING WEIGHTS
LOSS: 0.001191
EPOCH 2
TARGET: 
[ 0.  1.]
INPUT ACTIVATIONS
[-1. -1.  1.]
WEIGHTS:
[[-0.65934554 -1.78290126  0.        ]
 [ 0.07679915 -1.4334752   0.        ]
 [-0.15770106 -0.05936

'\nclass Node(Object):\n    def __init__(self):\n        \n    def \n'

In [4]:
class SigmoidNN(NN):
    def _activate(self, x):
        """
        override RelU with sigmoid
        """
        return self._sigmoid(x)
    
    def _derivative_activation(self, x):
        """
        Override RelU' with Sigmoid'
        """
        return self._derivative_sigmoid(x)
    
"""
Run the same test with sigmoid
"""
MLP = SigmoidNN(2, 1, 2, 2)
xor_inputs = [[1, 1], [-1, 1], [-1, -1], [1, -1]]
xor_labels = ([1, 0, 1, 0])
MLP.train(xor_inputs, xor_labels, epochs=100, lr=.3)

EPOCH 0
TARGET: 
[ 0.  1.]
WEIGHTS:
[[ 0.49999114  0.07880444  0.        ]
 [-0.28616675 -1.268467    0.        ]
 [ 2.41048899  1.01062492  0.        ]]
[]
[[-1.09087155  0.31398398]
 [ 0.71542081  0.35944917]
 [-0.02296056 -0.45859542]]
SOFTMAX_LAYER
[0.34856518373851364, 0.65143481626148636]
LOSS PER INSTANCE: 0.428578
DERIVATIVE LOSS: -1.535073
UPDATING WEIGHTS
LOSS: 0.428578
EPOCH 1
TARGET: 
[ 0.  1.]
WEIGHTS:
[[ 0.5018625   0.07617223  0.        ]
 [-0.28429539 -1.27109922  0.        ]
 [ 2.40861763  1.01325713  0.        ]]
[]
[[-1.06653772  0.33895635]
 [ 0.73976345  0.38443058]
 [-0.00319339 -0.43830955]]
SOFTMAX_LAYER
[0.34843673481798815, 0.6515632651820118]
LOSS PER INSTANCE: 0.428381
DERIVATIVE LOSS: -1.534770
UPDATING WEIGHTS
LOSS: 0.428381
EPOCH 2
TARGET: 
[ 0.  1.]
WEIGHTS:
[[ 0.5036851   0.07341906  0.        ]
 [-0.28247279 -1.27385239  0.        ]
 [ 2.40679503  1.0160103   0.        ]]
[]
[[-1.04175351  0.36346745]
 [ 0.76459007  0.40898362]
 [ 0.01695097 -0.4183871

In [228]:
class TanHNN(NN):
    
    def _activate(self, x):
        """
        Override with TanH
        """
        return np.tanh(x)
    
    def _derivative_activation(self, x):
        """
        Override with Derivative TanH (1 - tanH squared)
        """
        return 1 - x*x
    
"""
Run the same test with TanH
"""
MLP = TanHNN(2, 1, 2, 2)
xor_inputs = [[1, 1], [-1, 1], [-1, -1], [1, -1]]
xor_labels = ([1, 0, 1, 0])
MLP.train(xor_inputs, xor_labels, epochs=50, lr=.03)

EPOCH 0
TARGET: 
[ 0.  1.]
WEIGHTS:
[[-0.79098598 -0.05572377  0.        ]
 [ 0.08511857  0.25775903  0.        ]
 [-0.18411189 -1.29343291  0.        ]]
[]
[[ 0.59895566 -0.9057812 ]
 [ 0.34696668  0.45134984]
 [-0.47357902 -0.41719315]]
SOFTMAX_LAYER
[0.68401889935143889, 0.31598110064856111]
LOSS PER INSTANCE: 1.152073
DERIVATIVE LOSS: -3.164746
UPDATING WEIGHTS
LOSS: 1.152073
EPOCH 1
TARGET: 
[ 0.  1.]
WEIGHTS:
[[-0.81341844 -0.01999502  0.        ]
 [ 0.06268612  0.29348778  0.        ]
 [-0.16167943 -1.32916166  0.        ]]
[]
[[ 0.63180385 -0.90036212]
 [ 0.28495804  0.44112007]
 [-0.42135735 -0.40857797]]
SOFTMAX_LAYER
[0.72012928543371213, 0.27987071456628787]
LOSS PER INSTANCE: 1.273428
DERIVATIVE LOSS: -3.573078
UPDATING WEIGHTS
LOSS: 1.273428
EPOCH 2
TARGET: 
[ 0.  1.]
WEIGHTS:
[[-0.84084877  0.03564171  0.        ]
 [ 0.03525579  0.34912451  0.        ]
 [-0.1342491  -1.38479839  0.        ]]
[]
[[ 0.68169967 -0.89003912]
 [ 0.19802291  0.42313397]
 [-0.34955207 -0.393722

In [23]:
import math
import pandas as pd

def neighborhood2int(n):
    """
    For mapping neighborhoods into integer labels
    """
    return 1 if n == "Blmngtn" else 0

df = pd.DataFrame.from_csv("./data/housing_date_train_2_features.csv")
housing_df = df.loc[df['Neighborhood'].isin(["BrDale", "Blmngtn"])]

# Grab X and its labels as a single matrix
dataset = housing_df[["LotArea", "SalePrice", "Neighborhood"]].as_matrix()

# 'shuffle' the matrix to randomize the position of each sample in it
np.random.shuffle(dataset)

# Not sure why shuffling changed the type, but need to 
# change the type of each scalar in X for some numpy methods to work
X = dataset[:, :2].astype('int64')
# Encode the labels
y = [neighborhood2int(s) for s in dataset[:, 2]]

# Find the length of 80% of the dataset for training data
train_length = int(X.shape[0] * 0.8)

# split 80%/20% for train and test
train_X = X[:train_length]
test_X = X[train_length:]